name: calc
description: A simple CLI app to do quick calculations on the command-line.
version: 1.0.0
homepage: https://github.com/iamtheblackunicorn/Calc
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  pedantic: ^1.11.0
